Release 1.5.0
Esri/pyprt pull request #133
Opened 2021-12-20 09:44 UTC by clechot

2021-12-20 09:52 UTC, clechot commented
Do we want to mention https://github.com/Esri/pyprt/pull/130 in the CHANGELOG?

2022-01-04 12:21 UTC, mistafunk approved these changes
LGTM.

2022-01-05 13:33 UTC, mistafunk requested changes
* Looks good overall, see one inline comment...
* In the readme, we should remove "We only support Docker on Linux and Windows." in the docker section. Does not make any sense anymore after removing macOS support.
* Consider running our PyPRT-Docker pipeline before merging
* There are merge conflicts with develop, consider rebasing...

2022-01-05 13:33 UTC, mistafunk commented on README.md
> +   * Windows: `docker build --rm -f envs\windows\base\Dockerfile -t pyprt-base:windows-py3.6 --build-arg PY_VER=3.6 .`
For wheels on Windows, we use a different base image dockerfile: `Dockerfile-py` (prebuilt windows images provided by the python community)

2022-01-10 07:39 UTC, mistafunk approved these changes
Nice work, feel free to merge.

2022-01-10 07:42 UTC, merged