automate building docker images
Esri/pyprt pull request #82
Opened 2021-05-02 16:51 UTC by mistafunk

2021-05-18 06:19 UTC, clechot commented
Suggestion: would it be possible to deduplicate the yml files? I noticed that for one Python version, the yml environment files from each platform were the same. This has been done in the PyPRT examples repo.

2021-08-17 13:38 UTC, mistafunk commented
> Suggestion: would it be possible to deduplicate the yml files? I noticed that for one Python version, the yml environment files from each platform were the same. This has been done in the PyPRT examples repo.

Did not find an easy way to parametrize conda env files... let's do that in a separate issue.

2021-08-19 13:46 UTC, clechot requested changes
Could you also change the README at line 87 `devtoolset-9` instead of 8?

2021-08-19 13:46 UTC, clechot commented on README.md
> +    1. Install build dependencies for PyPRT: `.venv/bin/python -m pip install -r envs/centos7/wheel/requirements-py36.txt`
`requirements-py3.6.txt`

2021-08-19 13:46 UTC, clechot commented on README.md
>  1. First time only: run `conda env create --prefix ./env --file envs/centos7/py36-conda/environment.yml` to create a conda environment with all the required Python packages (adapt `centos7/py36-conda
-`envs/centos7/conda/environment-py3.6.yml`
-"adapt `centos7/py36-conda` ..." --> "adapt `centos7` and the `environment-py3.6.yml` to ..."

2021-08-19 13:46 UTC, clechot commented on README.md
> +1. The resulting package is written to the `./env-py36/conda-bld/{platform}` folder.
The folder is `./env/conda-bld/{platform}`, isn't it? I mean it depends on how you called it on step 3, right?

2021-08-19 13:46 UTC, clechot commented on README.md
> +   * Windows: `docker build --rm -f envs\windows\wheel\Dockerfile -t pyprt:windows-py36 --build-arg PY_VER=3.6 .`
Is it normal that on line 162 `PY_VER=36` (without the point) and on line 163 `PY_VER=3.6`(with a point)?

2021-08-19 13:46 UTC, clechot commented on README.md
> +    * Windows: `docker build --rm -f envs\windows\conda\Dockerfile -t pyprt:windows-py36-conda --build-arg PY_VER=3.6 .`
Is it normal that on line 173 `PY_VER=36` (without the point) and on line 174 `PY_VER=3.6`(with a point)?

2021-08-19 15:24 UTC, mistafunk commented on README.md
> +    1. Install build dependencies for PyPRT: `.venv/bin/python -m pip install -r envs/centos7/wheel/requirements-py36.txt`
done

2021-08-19 15:28 UTC, mistafunk commented on README.md
>  1. First time only: run `conda env create --prefix ./env --file envs/centos7/py36-conda/environment.yml` to create a conda environment with all the required Python packages (adapt `centos7/py36-conda
done

2021-08-19 15:29 UTC, mistafunk commented on README.md
> +1. The resulting package is written to the `./env-py36/conda-bld/{platform}` folder.
good catch, done

2021-08-19 15:30 UTC, mistafunk commented on README.md
> +   * Windows: `docker build --rm -f envs\windows\wheel\Dockerfile -t pyprt:windows-py36 --build-arg PY_VER=3.6 .`
good catch, done

2021-08-19 15:33 UTC, mistafunk commented on README.md
> +    * Windows: `docker build --rm -f envs\windows\conda\Dockerfile -t pyprt:windows-py36-conda --build-arg PY_VER=3.6 .`
done

2021-08-19 19:01 UTC, clechot approved these changes

2021-08-19 19:52 UTC, merged